### ISSUE TITLE
Create Docker Compose Configuration for MLflow Setup with UI, Backend, and Dashboard

### ISSUE THREAD

**Issue by habeshaethiopia** [habeshaethiopia/Fraud-detection-for-e-commerce#4]
We need a Docker Compose setup to containerize and deploy our MLflow application, including the MLflow UI, a Python backend server, and a frontend dashboard. The services should run on specific ports as outlined below for consistency across environments.

### Requirements:
1. **MLflow UI**:
   - Use the official MLflow Docker image or install MLflow via Python.
   - Run the MLflow UI on port `5000` inside the container and map it to `5000` on the host.
   - Configure a file-based backend store (e.g., `./mlruns`) and artifact storage (e.g., `./artifacts`).
   - Ensure the UI is accessible at `http://localhost:5000`.

2. **Python Backend (src/server.py)**:
   - Create a custom Docker image based on `python:3.9-slim`.
   - Copy the `src/server.py` file into the container.
   - Install necessary Python dependencies (e.g., via a `requirements.txt` file).
   - Configure the backend to run on port `5001` (update `src/server.py` if needed or pass as an argument).
   - Expose the backend on port `5001` and map it to `5001` on the host.
   - Ensure it’s accessible at `http://localhost:5001`.

3. **Dashboard (npm run dev)**:
   - Create a custom Docker image based on `node:18`.
   - Copy the dashboard source code (e.g., `package.json`, `src/`, etc.) into the container.
   - Install Node.js dependencies with `npm install`.
   - Run the dashboard in development mode using `npm run dev`, configured to use port `3000`.
   - Expose the dashboard on port `3000` and map it to `3000` on the host.
   - Ensure it’s accessible at `http://localhost:3000`.

4. **Docker Compose**:
   - Define all three services (MLflow UI, backend, dashboard) in a single `docker-compose.yml` file.
   - Use volume mappings for persistence (e.g., MLflow runs and artifacts).
   - Set up a shared network for inter-service communication.
   - Use environment variables where applicable (e.g., for port configuration).

### Acceptance Criteria:
- Running `docker-compose up` starts all services successfully.
- MLflow UI is accessible at `http://localhost:5000`.
- Backend server is accessible at `http://localhost:5001`.
- Dashboard is accessible at `http://localhost:3000`.
- Logs confirm all services are running without errors.
- Volume mounts persist MLflow data between container restarts.

### Example Deliverables:
1. **Docker Compose File (docker-compose.yml)**:
   ```yaml
   version: '3.8'
   services:
     mlflow-ui:
       image: ghcr.io/mlflow/mlflow:latest
       ports:
         - "5000:5000"
       volumes:
         - ./mlruns:/mlruns
         - ./artifacts:/artifacts
       command: mlflow ui --backend-store-uri /mlruns --default-artifact-root /artifacts --host 0.0.0.0 --port 5000

     backend:
       build:
         context: .
         dockerfile: Dockerfile.backend
       ports:
         - "5001:5001"
       volumes:
         - ./src:/app/src
       environment:
         - PORT=5001

     dashboard:
       build:
         context: .
         dockerfile: Dockerfile.dashboard
       ports:
         - "3000:3000"
       volumes:
         - ./dashboard:/app
   networks:
     - app-network

   networks:
     app-network:
       driver: bridge
   ```

2. **Dockerfile for Backend (Dockerfile.backend)**:
   ```Dockerfile
   FROM python:3.9-slim
   WORKDIR /app
   COPY requirements.txt .
   RUN pip install -r requirements.txt
   COPY src/ .
   ENV PORT=5001
   CMD ["python", "src/server.py"]
   EXPOSE 5001
   ```

3. **Dockerfile for Dashboard (Dockerfile.dashboard)**:
   ```Dockerfile
   FROM node:18
   WORKDIR /app
   COPY package.json package-lock.json ./
   RUN npm install
   COPY . .
   CMD ["npm", "run", "dev"]
   EXPOSE 3000
   ```

### Tasks:
- [ ] Create the `docker-compose.yml` file with all three services and specified ports.
- [ ] Create a `Dockerfile.backend` for the Python backend running on port 5001.
- [ ] Create a `Dockerfile.dashboard` for the Node.js dashboard running on port 3000.
- [ ] Test the setup locally to ensure all components work as expected.
- [ ] Document usage instructions in a `README.md` (e.g., how to build and run).

### Notes:
- Assumes `src/server.py` can read the `PORT` environment variable or be modified to use port 5001.
- Assumes the dashboard’s `npm run dev` script defaults to port 3000 (adjust if needed in `package.json` or config).
- Include a `requirements.txt` file for the backend and a `package.json` for the dashboard (assumed to exist).
- Add any additional dependencies (e.g., database) in the comments if required.

**Priority:** Medium  
**Due Date:** [Set a reasonable deadline, e.g., March 18, 2025]
